
package mvn

import mvnmod.builder.MavenCentralModule

object `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven-archive:jar:2.2.2` extends MavenCentralModule(
  "org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven-archive:jar:2.2.2",
  `org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.3`,
  `org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.3`,
  `org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.3`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven:jar:2.2.2`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api:jar:2.2.2`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven-archive:jar:2.2.2`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi:jar:2.2.2`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven-archive:jar:2.2.2`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven:jar:2.2.2`,
  `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven:jar:2.2.2`,
  `org.eclipse.aether:aether-api:jar:1.0.0.v20140518`,
  `org.eclipse.aether:aether-impl:jar:1.0.0.v20140518`,
  `org.eclipse.aether:aether-spi:jar:1.0.0.v20140518`,
  `org.eclipse.aether:aether-util:jar:1.0.0.v20140518`,
  `org.eclipse.aether:aether-connector-basic:jar:1.0.0.v20140518`,
  `org.eclipse.aether:aether-transport-wagon:jar:1.0.0.v20140518`,
  `org.apache.maven:maven-aether-provider:jar:3.2.5`,
  `org.apache.maven:maven-model:jar:3.2.5`,
  `org.apache.maven:maven-model-builder:jar:3.2.5`,
  `org.apache.maven:maven-repository-metadata:jar:3.2.5`,
  `org.apache.maven:maven-settings:jar:3.2.5`,
  `org.apache.maven:maven-settings-builder:jar:3.2.5`,
  `com.google.guava:guava:jar:18.0`,
  `org.codehaus.plexus:plexus-interpolation:jar:1.21`,
  `org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3`,
  `org.sonatype.plexus:plexus-cipher:jar:1.4`,
  `org.apache.maven.wagon:wagon-provider-api:jar:2.6`,
  `org.apache.maven.wagon:wagon-file:jar:2.6`,
  `commons-lang:commons-lang:jar:2.6`,
  `org.apache.maven.wagon:wagon-http-lightweight:jar:2.6`,
  `org.apache.maven.wagon:wagon-http-shared:jar:2.6`,
  `org.jsoup:jsoup:jar:1.7.2`,
  `commons-io:commons-io:jar:2.2`,
  `org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0.M1`,
  `javax.enterprise:cdi-api:jar:1.0`,
  `javax.annotation:jsr250-api:jar:1.0`,
  `javax.inject:javax.inject:jar:1`,
  `org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0.M1`,
  `org.codehaus.plexus:plexus-component-annotations:jar:1.5.5`,
  `org.codehaus.plexus:plexus-compiler-javac:jar:2.3`,
  `org.codehaus.plexus:plexus-compiler-api:jar:2.3`,
  `org.codehaus.plexus:plexus-utils:jar:3.0.20`
)
         